### ISSUE TITLE
Atom crushes when installing your package

### ISSUE THREAD

**Issue by mirzacmarius** [eerrecalde/bracket-matcher-highlight#1]
No error raising just ask me to close windows or keep it open.

**Comment by katrin-k** [comment]
Hi. I have the same issue. For me, it occurred after updating Atom from 1.10.x to 1.12.2. 

After the update, Atom alerted me that the bracket-matcher-highlight is not working properly (didn't note the exact error message, unfortunately) and recommended to rebuild the package. Did so. Rebuilding the package yielded no error message. But since then Atom ~~can't~~ couldn't be started. 
My System is OSX 10.11.6. 

(My solution for now: I removed all package related files from ~/.atom/packages, ~/.atom/.apm and several lose files inside ~.atom/compile-cache. So far no further problems.)

**Comment by eerrecalde** [comment]
Apologise @katrin-k and @mirzacmarius for the delay in coming back.. 
It seems to be related to a major change in the version of atom 1.12.x (As Katrin suggested)
You can for now just uninstalled it until I get it working :S
`apm uninstall bracket-matcher-highlight`

Will keep you updated on this

**Comment by eerrecalde** [comment]
Issue Fixed @mirzacmarius @katrin-k @aalsayyi
Please give it a try and let me know if you spot any issues.

Tested on Atom version 1.12.6
